import pytest
from fixtures.test_fixtures import mock_fixture

# fixtures.test_fixtures says it cannot be resolved, however it properly _is_ resolved, because the tests run fine
